"use client";

import React from 'react';
import { DecisionImpact, DecisionCategory } from '@/types/executive';
import { formatCurrency, formatNumber, cn } from '@/lib/utils';
import { ShieldAlert, TrendingUp, PauseCircle, ChevronDown, ChevronUp } from 'lucide-react';

interface DecisionImpactProps {
    data: DecisionImpact;
}

export function DecisionImpactCard({ data }: DecisionImpactProps) {
    return (
        <div className="bg-white p-6 rounded-2xl border border-slate-100 shadow-sm h-full flex flex-col">
            <div className="mb-6">
                <h3 className="text-lg font-semibold text-slate-900">Decision Impact</h3>
                <p className="text-sm text-slate-500">Net value generated by optimization actions ({data.period})</p>
            </div>

            <div className="flex items-end gap-3 mb-8">
                <span className="text-4xl font-bold text-slate-900 tracking-tight">
                    {formatCurrency(data.net_impact)}
                </span>
                <span className={cn(
                    "text-sm font-medium mb-1.5 px-2 py-0.5 rounded-full",
                    data.net_impact >= 0 ? "bg-emerald-50 text-emerald-600" : "bg-rose-50 text-rose-600"
                )}>
                    {data.net_impact >= 0 ? '+' : ''}{data.net_impact_pct.toFixed(1)}% revenue lift
                </span>
            </div>

            <div className="grid grid-cols-1 gap-4 flex-1">
                <DecisionRow
                    label="Bid Increases"
                    category={data.bid_ups}
                    icon={TrendingUp}
                    iconColor="text-emerald-500"
                    bgColor="bg-emerald-50"
                />
                <DecisionRow
                    label="Bid Decreases"
                    category={data.bid_downs}
                    icon={ChevronDown}
                    iconColor="text-amber-500"
                    bgColor="bg-amber-50"
                />
                <DecisionRow
                    label="Pauses"
                    category={data.pauses}
                    icon={PauseCircle}
                    iconColor="text-rose-500"
                    bgColor="bg-rose-50"
                />
                <DecisionRow
                    label="Negative Keywords"
                    category={data.negatives}
                    icon={ShieldAlert}
                    iconColor="text-purple-500"
                    bgColor="bg-purple-50"
                />
            </div>
        </div>
    );
}

function DecisionRow({
    label,
    category,
    icon: Icon,
    iconColor,
    bgColor
}: {
    label: string;
    category: DecisionCategory;
    icon: any;
    iconColor: string;
    bgColor: string;
}) {
    return (
        <div className="flex items-center justify-between p-3 rounded-xl border border-slate-50 hover:bg-slate-50/50 transition-colors">
            <div className="flex items-center gap-3">
                <div className={cn("p-2 rounded-lg", bgColor)}>
                    <Icon className={cn("w-5 h-5", iconColor)} />
                </div>
                <div>
                    <div className="text-sm font-medium text-slate-900">{label}</div>
                    <div className="text-xs text-slate-500">{category.count} decisions · {category.detail}</div>
                </div>
            </div>
            <div className="text-right">
                <div className={cn("text-sm font-semibold", category.impact >= 0 ? 'text-emerald-600' : 'text-slate-600')}>
                    {category.impact > 0 ? '+' : ''}{formatCurrency(category.impact)}
                </div>
            </div>
        </div>
    );
}
